### PR TITLE
Improves Apache install and shell code (GH-4)

### LINKED ISSUE #4: VM: File on system created by you or by a script.
```
$ vagrant destroy -f
$ vagrant up
==> default: Setting up apache2 (2.4.7-1ubuntu4.18) ...
==> default: Configuration file '/etc/apache2/sites-available/000-default.conf'
==> default:  ==> File on system created by you or by a script.
==> default:  ==> File also in package provided by package maintainer.
==> default:    What would you like to do about it ?  Your options are:
==> default:     Y or I  : install the package maintainer's version
==> default:     N or O  : keep your currently-installed version
==> default:       D     : show the differences between the versions
==> default:       Z     : start a shell to examine the situation
==> default:  The default action is to keep your current version.
==> default: *** 000-default.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package apache2 (--configure):
==> default:  EOF on stdin at conffile prompt
==> default: dpkg: dependency problems prevent configuration of libapache2-mod-php5:
==> default:  libapache2-mod-php5 depends on apache2 (>= 2.4); however:
==> default:   Package apache2 is not configured yet.
==> default: dpkg: error processing package libapache2-mod-php5 (--configure):
==> default:  dependency problems - leaving unconfigured
==> default: dpkg: dependency problems prevent configuration of php5:
==> default:  php5 depends on libapache2-mod-php5 (>= 5.5.9+dfsg-1ubuntu4.22) | libapache2-mod-php5filter (>= 5.5.9+dfsg-1ubuntu4.22) | php5-cgi (>= 5.5.9+dfsg-1ubuntu4.22) | php5-fpm (>= 5.5.9+dfsg-1ubuntu4.22); however:
==> default:   Package libapache2-mod-php5 is not configured yet.
==> default:   Package libapache2-mod-php5filter is not installed.
==> default:   Package php5-cgi is not installed.
==> default:   Package php5-fpm is not installed.
==> default: dpkg: error processing package php5 (--configure):
==> default:  dependency problems - leaving unconfigured
==> default: Setting up mysql-common (5.5.58-0ubuntu0.14.04.1) ...
==> default: No apport report written because the error message indicates its a followup error from a previous failure.
==> default: No apport report written because the error message indicates its a followup error from a previous failure.
...
```

### LINKED ISSUE #6: invoke-rc.d: initscript mysql, action "start" failed
```
$ vagrant up
...
==> default: 2017-10-27 17:16:52 0 [Note] /usr/sbin/mysqld (mysqld 5.6.33-0ubuntu0.14.04.1) starting as process 11283 ...
==> default: start: Job failed to start
==> default: invoke-rc.d: initscript mysql, action "start" failed.
==> default: dpkg: error processing package mysql-server-5.6 (--configure):
==> default:  subprocess installed post-installation script returned error exit status 1
==> default: Creating config file /etc/php5/mods-available/gd.ini with new version
==> default: php5_invoke: Enable module gd for cli SAPI
==> default: php5_invoke: Enable module gd for apache2 SAPI
==> default: Creating config file /etc/dbconfig-common/config with new version
==> default: apache2_invoke: Enable configuration javascript-common
==> default: dbconfig-common: writing config to /etc/dbconfig-common/phpmyadmin.conf
==> default: Creating config file /etc/dbconfig-common/phpmyadmin.conf with new version
==> default: Creating config file /etc/phpmyadmin/config-db.php with new version
==> default: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2).
```

### PR DESCRIPTION
**Pull request by kenorb**
Improving provisioning process and the shell code syntax.

Tested by `vagrant destroy -f && vagrant up` and the errors doesn't happen.

- Fixes #4 and Fixes #6

### CODE REVIEW

**Comment by BorislavZlatanov** [comment]
Thanks.

Just one question that I had: recently we explicitly specified the MySQL server version to be 5.6 because for some reason just `mysql-server` was installing version 5.5 (if my memory is not failing me). When you bootstrap with just `mysql-server`, does it install version 5.6?

**Comment by kenorb** [comment]
I think the problem of 5.5 could be fixed by `vagrant box update` (mine is `20171023.0.0`). Using specific version of MySQL could cause some problems in the future version of `ubuntu/trusty64` boxes. Could it be that apache package be pointing to general `mysql-server` which could cause the conflicts as described in #6. Try testing it after updating VM box whether you got any errors. On mine after the change it started to work. We can always do another fix on top of it.
I don't want to change too many things at this point, however when this is merged, I could have a test and look different issues which I had.

**Comment by BorislavZlatanov** [comment]
I'm not able to test currently, but I'm thinking we want to use the same MySQL server version locally as we use on the server. Currently that is 5.6. So unless there is any other specific issue, I think it will be best if we specify the version and update the vagrant config accordingly when we update the server software. I realize we may be limited in the PHP (currently 7.1 on the server) and Apache (2.4) versions, though.

What do you think?

**Comment by kenorb** [comment]
I think it's good to use the latest stable version which is provided by the main package `mysql-server` to avoid any outdated software which could be not supported, also to avoid any bugs. If you install older MySQL, then it can cause more complex dependency issues like forcing PHP mysql client to be older and Apache to be older. Also using older packages, could cause some extra problems, unexpected crashes and vulnerabilities. It's better to follow what's provided by default to make it simple, unless we'll have any specific issues. Software on the servers can be always updated.

If you'll find any issues with the existing config, please raise a new issue, so we can have a look at it.

**Pull request merged**
